[phases.setup]
[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "npm install --prefix frontend"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend"
]

[start]
cmd = "python run.py"